project:
  type: book
  output-dir: _book

book:
  title: "TBCMP Opportunity Analysis"
  author: "Tampa Bay Estuary Program"
  date: today
  chapters:
    - index.qmd
    - current_summaries.qmd
    - part: "Opportunity Maps"
      chapters:
        - oppmap_citrus.qmd
    - part: "Steps"
      chapters:
        - 01_inputs.qmd
        - 02_current_layers.qmd
        - 03_current_summaries.qmd
        - 04_opportunities_maps.qmd
        - 05_restoration_maps.qmd

bibliography: refs.bib
link-citations: true
citations-hover: false
citation-location: margin

format:
  html:
    theme: default
    css: tbcmp-brand.css
    toc: true
    toc-depth: 3
    code-fold: true
    number-depth: 1

execute:
  echo: false
  warning: false
  message: false